name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: [ "self-hosted", "Linux", "X64" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker CLI for Minikube
        run: |
          echo "Switching Docker to Minikube's Docker daemon"
          eval $(minikube docker-env)

      # --------------------------------------------------
      # 1. Log in to Docker Hub (once, for both images)
      # --------------------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --------------------------------------------------
      # 2. Build & push frontend image
      # --------------------------------------------------
      - name: Build frontend image
        run: |
          docker build \
            -t hamza2533/my-react-frontend:latest \
            ./app/frontend

      - name: Push frontend image
        run: |
          docker push hamza2533/my-react-frontend:latest

      # --------------------------------------------------
      # 3. Build & push backend image
      # --------------------------------------------------
      - name: Build backend image
        run: |
          docker build \
            -t hamza2533/my-node-backend:latest \
            ./app/backend

      - name: Push backend image
        run: |
          docker push hamza2533/my-node-backend:latest

      # --------------------------------------------------
      # 4. Deploy to Kubernetes
      # --------------------------------------------------
      - name: Deploy frontend
        run: |
          kubectl apply -f service-frontend.yaml
          kubectl apply -f deployment-frontend.yaml

      - name: Deploy backend
        run: |
          kubectl apply -f service-backend.yaml
          kubectl apply -f deployment-backend.yaml

      - name: Verify deployment
        run: kubectl get pods -o wide
